{% set name = "pycoal" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycoal-{{ version }}.tar.gz
  sha256: 330f88043f29b027e49daa31a749af6ed23deb18059ac8ba24949a01d4dc8a6f

build:
  number: 1004
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - spectral

test:
  imports:
    - pycoal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/capstone-coal/pycoal/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Python toolkit for characterizing Coal and Open-pit surface mining impacts on American Lands'
  description: |
    pycoal is a Python library for processing hyperspectral imagery from remote sensing devices such 
    as the Airborne Visible/InfraRed Imaging Spectrometer (AVIRIS) and AVIRIS-Next Generation 
    enabling scientific analysis of Coal and Open-pit surface mining impacts on American Lands (COAL).
  doc_url: http://pycoal.readthedocs.io/
  dev_url: https://github.com/capstone-coal/pycoal/

extra:
  recipe-maintainers:
    - lewismc
