travis:
  secure:
    BINSTAR_TOKEN: eQSvzcwGvoWOi2yjFIjwzn50YELfJgqXwtZQ5k4/wCpDUS/bGFAi0AZfGJWWpmnUZ7GozKfcTplDEyKpEiDCV6KRpJDL8Wbuttk/jMl6hiQ3CHWoamUEoId/5Yfl56yyJTLz5DPQpeChDefZUMXOznVJhRPhJiP6/5O5vuQUkud3F10kI/m+OFrIQMwOvKIMONoFQV6t5y4gFyqiwKG3nyTdBwcFy9ThZdRtzMt1oUhjNPcvQI8UcMsy1vBUA5flmQHkutmu0GCjtu0F0Rho1wgFlsRf3YCKdduFtE3kdJ7l4m9kpDC2viyvydX+oUUdYtiHAZiMAJ6i7HkSwTzXNSyxlMqvPZr2U9xEGMpCrqvK1b70q3/T+e3y2m9jbDn6Z5vX6bZm0NDNGl5UnFqSz7zsbmOS8RehrA0FcKTXObiOAIxbJ6AgdDV32bPIat5zbW/mwhehIiEijHtYxfUx/Q8f95GmiJyI2sSqAQ2SlQuODwstRYNLTIvC9Q49ivWh5I+kZPOjCYSH8VsU9W2Do6ExIyQzqAl4XWtIamUIzOXwux1kNfVnQMyDMbGF/9ctzJhkXLqdroKMy1MhZDU5p3K1SRwKoVfVCNLGWyA2ERbcRt5WbXSOeBOHNTkpiyLIlKzqLbJ4GUByNdpVeK0blXsUWnSEKMjoQBAJe4Kp8sk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
