appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CFmhuAG5/z1Oz5PAJb+pxzv1TqU17qf1h06OBnZudtkC8X3dUCTyD2s8fpUP1sDbmzQBlaMiD9kuaWAwplRHpQ14rod2IAcrITvAwbzCuW80B4yV0IcDz8uqLCF/mhP5DiRm7h7pf9fDQgpUNj/hzqm50EMhKa06FzGyLxvzYdoTmpzQly4y/iKBbS1v0fRiuBZG3wsMZhARjhT6IFdT+aUEDfYyjinZ2An3iy8OY+lX3He4XKPrJ0DVtWV81wry3Q4XBz/LYIDq3/GhNvTLxlt9Ihcpf8+PN5GrLxnJiQ9JHvp0oERb7g1T3URjWTjWFIQP/R2SeruIQnjNkcLV5S20QKsYoaOzANpQPN5/69/qdkLa4HfFs5znHWW7TjmgvoNNGghTzHHtVqv9OmQ+bRI/rgsb48AzHMYRve5DjixuHXZIVufmFRhGwef7QEsdSC7EAznJ+g7UYl0zk++E60cd/v4PoTuf0/4vKThOe487uGfH+84pq7i6/GLAUpCRuDmsZm+VljvJSabRrGc+qZXnejiiLeFUYJzp+H2p+ktUhdh0c3M10DJ08aKiiX3qfjBxhB2z0rlDFTq8lyfnH6s88L6E6RNPiewIpGJgz7WIlSiROs5zsjmZlVtGEtUiWhLhAXPN7ypoqABR5pnR6rR/MTkBlZUDnY0yvhMTpfk=}
