travis:
  secure:
    BINSTAR_TOKEN: gTvfGtlAFuwOVhanz3pqaNSJD4r4Bp508juUfq+5qFdtEVrOPEDavyuX1/TGUkot3xn6k2KyCkBN+u7wG0N+vMKmcPtgv+/CWXHbnxwQ+4bCt4lHVByhCbs5FRjC7vvxhzdxU2aPCw51OHtGvK7iTkeKB/buAAeTWoL1tEucR1j0kmG8h/1M00+8oZb2anD2xOqVhUWuCjgzV0oUGLwOEoZvAKH0H/ul8jc7AbUJMuzmlYEIocJOW2+DPVGnrYkB9BI5XwS7Ynhq+oXUfa1bsjT92zzbf67FunjH/U0XXXJt2FuUvkjkogkT7TcrHBwOnDvWlaLwSY6FSxdfuLW8B74LLr4Oiz1pQjMEo9KA9ehOHPeo3o6NGie0qKga4gDZe1LrJb//wXFxzoI0Vok86JH7ZMaiqFO94cZXCnjdymVNll7FmfrxZlzWQaeo0N8llSeM4r4OXOaqrkqHCXAKkn/lOeXJ9AVZJiJccvtksRWF0N+3O9XqZ9jOqxcxscyviS+DIX/mw73LBBGCYIAgFD14AwrIi6dnU0D8QfCVj/EZHOEI1fHazUY42DPECy+X3DMMTaVud3iMQ3iVwdyqqG05A0DZsn76HUmHod8rPOYqYA/m3giIl6kTGyoQUX7YOPuiiU79YzyvKT79OzepsjfWmghzDvsm0RZTXlSoCho=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
